/**
 * UI-only Spanish strings.
 *
 * Anything derived from the movie row (title, date, venue, runtime, fórmula)
 * lives in lib/format.ts and is built from movie data at render time.
 * This file holds editorial copy, labels, terminal-state phrasings, and
 * brand/venue constants that aren't part of the movie schema.
 */
export const copy = {
  htmlLang: "es",
  meta: {
    descriptionFallback:
      "Estreno único del documental CUATRO de Jose Javier Diaz.",
  },
  brand: {
    wordmark: "CUATRO",
  },
  skipLink: "Saltar al contenido",
  header: {
    myTickets: "MIS BOLETOS",
  },
  hero: {
    cta: "COMPRAR ENTRADAS",
    subtitle: "LA BANDA SONORA DE LA VIDA",
    scrollHint: "DESPLAZAR",
  },
  note: {
    sectionLabel: "NOTA DEL PROGRAMADOR",
    body: "Una sola función. Una sola sala. Cuatro es el documental que acompaña al disco homónimo de Jose Javier Diaz: cuatro piezas, cuatro estaciones, cuatro direcciones. Una hora exacta dentro del estudio, del estanque y de la montaña, filmada entre dos solsticios. Esta es la única proyección programada antes de que la película descanse.",
    benefit: "A beneficio de la Casa de Jose",
  },
  tracklist: {
    sectionLabel: "TRACKLIST",
    rows: [
      { n: "01", title: "AL ORIENTE PRIMAVERA", duration: "09:42" },
      { n: "02", title: "VERANO BOGANDO AL NORTE", duration: "11:08" },
      { n: "03", title: "OTOÑO MIRANDO AL SUR", duration: "12:23" },
      { n: "04", title: "RISAS DE INVIERNO AL OCCIDENTE", duration: "13:55" },
    ],
  },
  footer: {
    mapLink: "CÓMO LLEGAR",
    mapHref: "https://maps.app.goo.gl/m3GkfvPpauBMkCyF8",
    rights: "© 2026 JOSE JAVIER DIAZ · TODOS LOS DERECHOS RESERVADOS",
  },
  states: {
    soldOut: {
      label: "AGOTADO",
      body: "Si una butaca se libera, volverá a estar disponible aquí.",
    },
    passed: {
      label: "LA FUNCIÓN YA PASÓ",
      body: "Gracias a quienes asistieron al estreno único de CUATRO.",
    },
    error: {
      body: "No pudimos cargar la información de la función. Intenta de nuevo en un momento.",
      retry: "REINTENTAR",
    },
  },
  seats: {
    pageTitle: "ELIGE TUS BUTACAS",
    screenLabel: "PANTALLA",
    legend: {
      available: "Disponible",
      selected: "Tu selección",
      held: "Reservada",
      taken: "Vendida",
      accessible: "Accesible",
      label: "LEYENDA",
    },
    cart: {
      emptyHeading: "Elige tus butacas.",
      emptyBody: "Tienes 10 minutos cuando empieces.",
      timerPrefix: "TIEMPO RESTANTE",
      maxNotice: "Máximo 8 butacas por compra.",
      expiredNotice: "Tu reserva ha caducado. Estamos liberando las butacas…",
      conflictNotice: "Alguien tomó esa butaca antes que tú. La quitamos de tu selección.",
      continue: "CONTINUAR",
      removeAria: (label: string) => `Quitar butaca ${label} de tu reserva.`,
      countSingular: (n: number) => `${n} BUTACA`,
      countPlural: (n: number) => `${n} BUTACAS`,
    },
    a11y: {
      gridName: "Plano de butacas",
      seatStatus: {
        available: (label: string) => `Butaca ${label}, disponible.`,
        selected: (label: string) => `Butaca ${label}, seleccionada.`,
        held: (label: string) => `Butaca ${label}, reservada por otro comprador.`,
        taken: (label: string) => `Butaca ${label}, vendida.`,
      },
      added: (label: string) => `Butaca ${label} añadida a tu reserva.`,
      removed: (label: string) => `Butaca ${label} retirada de tu reserva.`,
    },
  },
  checkout: {
    timerPrefix: "TIEMPO RESTANTE",
    eyebrow: "RESUMEN DE TU RESERVA",
    tableSeats: "BUTACAS",
    tablePrice: "PRECIO",
    totalLabel: "TOTAL",
    payCta: (total: string) => `PAGAR · ${total}`,
    payingLabel: "CONECTANDO…",
    backLink: "← MODIFICAR BUTACAS",
    trustLine: "Tu reserva queda confirmada al verificar el comprobante.",
    payError: "No pudimos iniciar el pago. Intenta de nuevo.",
    expiredHeading: "Tu reserva ha caducado.",
    expiredBody: "Vuelve a elegir butacas.",
    expiredCta: "ELEGIR BUTACAS →",
    emptyHeading: "No hay butacas en tu reserva.",
    emptyCta: "ELEGIR BUTACAS →",
    instructions: {
      title: "TRANSFIERE EL PAGO",
      body: "Realiza la transferencia con los datos abajo y luego sube tu comprobante.",
      referencePrefix: "REFERENCIA",
      referenceNote:
        "Importante: escribe esta REFERENCIA en la descripción (detalle/concepto) de la transferencia. La verificamos para confirmar tu pago.",
      accountLabel: "CUENTA",
      amountLabel: "MONTO",
      copy: "COPIAR",
      copied: "COPIADO ✓",
    },
    upload: {
      label: "SUBIR COMPROBANTE",
      cta: "VERIFICAR PAGO",
      pickAnother: "SUBIR OTRO COMPROBANTE",
      tooLarge: "Máximo 5 MB.",
      wrongType: "Solo PNG o JPG.",
    },
    verifying: "Verificando comprobante…",
    rejected: {
      attemptsLeft: (n: number) => `Intentos restantes: ${n}`,
      exhausted: "Agotaste los intentos. Vuelve a elegir butacas.",
      expired: "Tu reserva expiró. Elige butacas de nuevo.",
    },
    softCap: "Estamos revisando tu pago — te avisaremos por correo cuando esté listo.",
  },
  success: {
    eyebrow: "TU RESERVA ESTÁ HECHA",
    heading: "NOS VEMOS EN LA SALA.",
    body: "Te enviamos una copia por correo. En la puerta te buscarán por tu nombre y te indicarán tu butaca. No hace falta imprimir nada.",
    stubLabel: "BUTACA",
    stubOrderLabel: "ORDEN",
    stubGuestLabel: "A NOMBRE DE",
    stubGuestPlaceholder: "—",
    resendCta: "REENVIAR CORREO",
    resendSentLabel: "ENVIADO ✓",
    myTicketsCta: "VER MIS BOLETOS →",
    emptyHeading: "No encontramos esta reserva.",
    emptyBody: "Si acabas de comprar, vuelve a abrir el enlace del correo. Si no, elige tus butacas desde la página principal.",
    emptyCta: "IR AL INICIO →",
  },
  myTickets: {
    eyebrow: "MIS BOLETOS",
    heading: "TU HISTORIAL.",
    body: "Cada reserva está aquí. Reenvía el correo si necesitas la confirmación de nuevo. En la puerta te buscarán por tu nombre.",
    cardSeatsLabel: "BUTACAS",
    cardOrderLabel: "ORDEN",
    cardTotalLabel: "TOTAL",
    cardViewTickets: "VER ENTRADAS →",
    pastTag: "FUNCIÓN PASADA",
    emptyHeading: "Aún no tienes boletos.",
    emptyBody: "Cuando compres entradas para CUATRO aparecerán aquí.",
    emptyCta: "IR AL CINE →",
    errorHeading: "No pudimos cargar tus boletos.",
    errorBody: "Intenta de nuevo en un momento.",
    errorCta: "REINTENTAR",
  },
  signin: {
    eyebrow: "INICIA SESIÓN",
    heading: "ENTRA A LA SALA.",
    body: "Usamos tu cuenta solo para emitir tus boletos y buscarte en la puerta.",
    googleCta: "CONTINUAR CON GOOGLE",
    dividerLabel: "O CON CORREO",
    nameLabel: "NOMBRE COMPLETO",
    namePlaceholder: "TU NOMBRE COMO APARECE EN TU IDENTIFICACIÓN",
    emailLabel: "CORREO",
    emailPlaceholder: "TU@CORREO.COM",
    passwordLabel: "CONTRASEÑA",
    passwordHint: "MÍNIMO 8 CARACTERES.",
    signinCta: "INICIAR SESIÓN",
    signupCta: "CREAR CUENTA",
    submittingLabel: "CONECTANDO…",
    toggleToSignup: "¿AÚN NO TIENES CUENTA? CREAR CUENTA →",
    toggleToSignin: "¿YA TIENES CUENTA? INICIAR SESIÓN →",
    privacy: "AL CONTINUAR ACEPTAS RECIBIR EL CORREO DE CONFIRMACIÓN.",
    backLink: "← VOLVER AL INICIO",
    genericError: "NO PUDIMOS COMPLETAR LA OPERACIÓN.",
    networkError: "SIN CONEXIÓN CON EL SERVIDOR.",
  },
  cancel: {
    eyebrow: "PAGO CANCELADO",
    activeHeading: "TU RESERVA SIGUE EN PIE.",
    activeBody: "Las butacas continúan apartadas para ti. Puedes volver al pago o cambiarlas mientras quede tiempo.",
    expiredHeading: "TU RESERVA HA CADUCADO.",
    expiredBody: "Las butacas vuelven a estar disponibles para otros. Elige de nuevo cuando quieras.",
    timerPrefix: "TIEMPO RESTANTE",
    retryCta: "VOLVER AL PAGO →",
    changeCta: "MODIFICAR BUTACAS",
    pickAgainCta: "ELEGIR BUTACAS →",
    seatsLabel: "BUTACAS",
  },
} as const;
